### ISSUE TITLE
multiline secrets are only to be fetched from default namespace

### ISSUE THREAD

**Issue by mvvveen** [SparebankenVest/akv2k8s-website#12]
I am unable to fetch the secret if it is in a namespace

for instance this secret is created in the  namespace foo
so if i do 
kubectl get akvs -n foo 
i get 
global-sa-account          my-very-secret-vault global-sa-account                        global-sa-account   2021-02-25T20:25:44Z

and it also exist as a secret in the namespace

kubectl get secrets -n foo
global-sa-account                    Opaque 2 105d

i reference the secret like so
              azureFile:
                secretName: global-sa-account
                shareName: some share
                readOnly: false

but in the logging i get
 MountVolume.SetUp failed for volume "volume" : Couldn't get secret default/global-sa-account

this worked fine in version akv2k8s-1.1.26
and is a problem in akv2k8s-1.1.28

**Comment by torresdal** [comment]
could you please post this issue to the https://github.com/SparebankenVest/azure-key-vault-to-kubernetes repo? This repo is just for the akv2k8s docs...

**Comment by mvvveen** [comment]
Sorry for that also i found out is unrelated.
https://github.com/Azure/AKS/issues/2108
