### ISSUE TITLE
Polling interval

### ISSUE THREAD

**Issue by cveld** [SparebankenVest/akv2k8s-website#27]
Can you add to your documentation what the polling interval is?
Have you considered eventgrid eventing?

**Comment by pannonsystems** [comment]
It would be really useful to be able to know where and how to configure the sync schedule at the global level as default and at the actual AzureKeyVaultSecret entry individually. It would bring better control over these entries and how they are sync-ed. Maybe like a cron type schedule setting.

It could help avoiding extremely frequent synchronization like (x1501 over 125m)

**Comment by vivekharrai** [comment]
how to check at what interval ak2k8s controller and injektor are polling to Azure key-vault. I tried to update an existing secret, however the new value was not fetched inside the cluster.

**Comment by tspearconquest** [comment]
@cveld its in the helm chart documentation: https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/akv2k8s/README.md

@pannonsystems You can configure the controller sync. By default, it's 30 seconds.

@vivekharrai As mentioned above, controller default is 30 seconds. The env-injector do not sync; when the pod is started is the only time that the secret is retrieved with the env-injector; if you update the secret in Keyvault, then you must restart the workload to get the new secret.
