### ISSUE TITLE
Is it possible to use Akv2K8s as dependency

### ISSUE THREAD

**Issue by avera813** [SparebankenVest/akv2k8s-website#3]
Installation guide recommends installing library through series of helm commands. I know I can install Akv2k8s as a dependency in Helm chart, but is the separate namespace really required? Is there any documentation or feature around using it through existing helm chart?

My main chart needs to be in default, but want akv2k8s to work properly.

**Comment by torresdal** [comment]
@avera813 as for dedicated namespace: https://akv2k8s.io/installation/requirements/#dedicated-namespace-for-akv2k8s

So it depends on how / what you will use akv2k8s for. If you need to customize to your needs, I recommend cloning the repository or use `helm template` to output everything you need - and then change as you like.

Saying that, I would advice against it - but the choice is your to make.
