### ISSUE TITLE
Unable to get controller pod up and running

### ISSUE THREAD

**Issue by abudavis** [SparebankenVest/akv2k8s-website#63]
App version: 	1.4.0 
Openshift: 4.10.30

Install worked but controller pod keeps restarting and finally crashes, see log below. Any ideas how to get this to work? 

Command ran:

```
helm repo add spv-charts https://charts.spvapi.no
helm repo update
helm upgrade --install akv2k8s spv-charts/akv2k8s \
  --namespace akv2k8s \
  --set global.logLevel=trace \
  --set global.keyVaultAuth=environment \
  --set global.env.AZURE_TENANT_ID=redacted \
  --set global.env.AZURE_CLIENT_ID= redacted \
  --set global.env.AZURE_CLIENT_SECRET=redacted
```

`1
I0621 17:11:19.126302 1 main.go:103] "log settings" format="text" level="6"
2
I0621 17:11:19.126395 1 version.go:31] "version info" version="1.4.0" commit="15d87b2" buildDate="2022-12-08T21:18:59Z" component="controller"
3
W0621 17:11:19.126636 1 client_config.go:617] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
4
I0621 17:11:19.127564 1 main.go:168] "Creating event broadcaster"
5
I0621 17:11:19.127707 1 main.go:219] "checking credentials by getting authorizer"
6
I0621 17:11:19.380271 1 controller.go:167] "setting up event handlers"
7
I0621 17:11:19.380308 1 controller.go:178] "starting azurekeyvaultsecret controller"
8
I0621 17:11:19.380467 1 reflector.go:221] Starting reflector *v1.ConfigMap (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
9
I0621 17:11:19.380526 1 reflector.go:257] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
10
I0621 17:11:19.380467 1 reflector.go:221] Starting reflector *v2beta1.AzureKeyVaultSecret (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
11
I0621 17:11:19.380559 1 reflector.go:257] Listing and watching *v2beta1.AzureKeyVaultSecret from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
12
I0621 17:11:19.380689 1 reflector.go:221] Starting reflector *v1.Secret (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
13
I0621 17:11:19.380710 1 reflector.go:257] Listing and watching *v1.Secret from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
14
I0621 17:11:19.388789 1 round_trippers.go:553] GET https://172.30.0.1:443/apis/spv.no/v2beta1/azurekeyvaultsecrets?limit=500&resourceVersion=0 200 OK in 7 milliseconds
15
I0621 17:11:19.389411 1 azureKeyVaultSecret.go:49] "adding to queue" azurekeyvaultsecret="akv2k8s/secret-sync"
16
I0621 17:11:19.393843 1 round_trippers.go:553] GET https://172.30.0.1:443/apis/spv.no/v2beta1/azurekeyvaultsecrets?allowWatchBookmarks=true&resourceVersion=585369369&timeout=8m1s&timeoutSeconds=481&watch=true 200 OK in 4 milliseconds
17
I0621 17:11:19.464005 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/configmaps?limit=500&resourceVersion=0 200 OK in 83 milliseconds
18
I0621 17:11:19.480569 1 shared_informer.go:285] caches populated
19
I0621 17:11:19.528193 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/secrets?limit=500&resourceVersion=0 200 OK in 147 milliseconds
20
I0621 17:11:20.237239 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/configmaps?allowWatchBookmarks=true&resourceVersion=585369368&timeout=9m42s&timeoutSeconds=582&watch=true 200 OK in 1 milliseconds
21
I0621 17:11:20.935142 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/secrets?allowWatchBookmarks=true&resourceVersion=585369355&timeout=8m19s&timeoutSeconds=499&watch=true 200 OK in 0 milliseconds
22
I0621 17:11:20.981329 1 shared_informer.go:285] caches populated
23
I0621 17:11:20.981380 1 shared_informer.go:285] caches populated
24
I0621 17:11:20.981394 1 controller.go:196] "starting azure key vault secret queue"
25
I0621 17:11:20.981411 1 controller.go:199] "starting azure key vault deleted secret queue"
26
I0621 17:11:20.981420 1 controller.go:202] "starting azure key vault queue"
`

**Comment by tspearconquest** [comment]
Hard to read the log, so I took the liberty of formatting it

```
1 I0621 17:11:19.126302 1 main.go:103] "log settings" format="text" level="6"
2 I0621 17:11:19.126395 1 version.go:31] "version info" version="1.4.0" commit="15d87b2" buildDate="2022-12-08T21:18:59Z" component="controller"
3 W0621 17:11:19.126636 1 client_config.go:617] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
4 I0621 17:11:19.127564 1 main.go:168] "Creating event broadcaster"
5 I0621 17:11:19.127707 1 main.go:219] "checking credentials by getting authorizer"
6 I0621 17:11:19.380271 1 controller.go:167] "setting up event handlers"
7 I0621 17:11:19.380308 1 controller.go:178] "starting azurekeyvaultsecret controller"
8 I0621 17:11:19.380467 1 reflector.go:221] Starting reflector *v1.ConfigMap (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
9 I0621 17:11:19.380526 1 reflector.go:257] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
10 I0621 17:11:19.380467 1 reflector.go:221] Starting reflector *v2beta1.AzureKeyVaultSecret (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
11 I0621 17:11:19.380559 1 reflector.go:257] Listing and watching *v2beta1.AzureKeyVaultSecret from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
12 I0621 17:11:19.380689 1 reflector.go:221] Starting reflector *v1.Secret (30s) from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
13 I0621 17:11:19.380710 1 reflector.go:257] Listing and watching *v1.Secret from pkg/mod/k8s.io/client-go@v0.25.5/tools/cache/reflector.go:169
14 I0621 17:11:19.388789 1 round_trippers.go:553] GET https://172.30.0.1:443/apis/spv.no/v2beta1/azurekeyvaultsecrets?limit=500&resourceVersion=0 200 OK in 7 milliseconds
15 I0621 17:11:19.389411 1 azureKeyVaultSecret.go:49] "adding to queue" azurekeyvaultsecret="akv2k8s/secret-sync"
16 I0621 17:11:19.393843 1 round_trippers.go:553] GET https://172.30.0.1:443/apis/spv.no/v2beta1/azurekeyvaultsecrets?allowWatchBookmarks=true&resourceVersion=585369369&timeout=8m1s&timeoutSeconds=481&watch=true 200 OK in 4 milliseconds
17 I0621 17:11:19.464005 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/configmaps?limit=500&resourceVersion=0 200 OK in 83 milliseconds
18 I0621 17:11:19.480569 1 shared_informer.go:285] caches populated
19 I0621 17:11:19.528193 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/secrets?limit=500&resourceVersion=0 200 OK in 147 milliseconds
20 I0621 17:11:20.237239 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/configmaps?allowWatchBookmarks=true&resourceVersion=585369368&timeout=9m42s&timeoutSeconds=582&watch=true 200 OK in 1 milliseconds
21 I0621 17:11:20.935142 1 round_trippers.go:553] GET https://172.30.0.1:443/api/v1/secrets?allowWatchBookmarks=true&resourceVersion=585369355&timeout=8m19s&timeoutSeconds=499&watch=true 200 OK in 0 milliseconds
22 I0621 17:11:20.981329 1 shared_informer.go:285] caches populated
23 I0621 17:11:20.981380 1 shared_informer.go:285] caches populated
24 I0621 17:11:20.981394 1 controller.go:196] "starting azure key vault secret queue"
25 I0621 17:11:20.981411 1 controller.go:199] "starting azure key vault deleted secret queue"
26 I0621 17:11:20.981420 1 controller.go:202] "starting azure key vault queue"
```

**Comment by tspearconquest** [comment]
Can you provide the output from `kubectl describe pod <pod-name> -n akv2k8s` please? I'm interested to see the exit code of the pod when it crashes.

**Comment by abudavis** [comment]
> Can you provide the output from `kubectl describe pod <pod-name> -n akv2k8s` please? I'm interested to see the exit code of the pod when it crashes.

@tspearconquest Thanks for looking at this, here is the output attached:
[ocdescribepod.yaml.zip](https://github.com/SparebankenVest/akv2k8s-website/files/11849866/ocdescribepod.yaml.zip)

**Comment by tspearconquest** [comment]
You're welcome.

From your output at the bottom:

```
  Warning  Unhealthy       6s (x12 over 63s)  kubelet            Readiness probe failed: Get "http://10.131.0.80:9000/healthz": dial tcp 10.131.0.80:9000: connect: connection refused
  Warning  Unhealthy       6s (x6 over 56s)   kubelet            Liveness probe failed: Get "http://10.131.0.80:9000/healthz": dial tcp 10.131.0.80:9000: connect: connection refused
```

The health probes are failing, and this is causing the issue you're seeing.

Based on some comments in the default values.yaml, I think the controller ports only function if you enable metrics, so try adding `--set controller.metrics.enabled=true` to your helm command line and let us know if it still crashes.

**Comment by abudavis** [comment]
@tspearconquest Thanks a lot! That worked :) Do you know if its somehow possible to sync all secrets in Azure key vault as k8s secrets without specifying the secret name itself in "AzureKeyVaultSecret" definition as this would save us some effort every time a secret is added on Azure?

**Comment by tspearconquest** [comment]
Unfortunately I'm not sure, as the env injector is the only thing we use in my work environment currently.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abudavis** [comment]
@tspearconquest I've heard that some folks run just the controller and not the injector, wonder what is the use case there!?

**Comment by tspearconquest** [comment]
One use case is to support apps that don't take config via environment vars.

Example: gitlab kubernetes agent by default uses a file backed by a Kubernetes secret to store the agent registration token, so one could put the token in keyvault and sync the keyvault secret to the cluster, which will make rotation easier.

________________________________
