### ISSUE TITLE
Support for auto sync of multiple secrets

### ISSUE THREAD

**Issue by abudavis** [SparebankenVest/akv2k8s-website#64]
App version: 1.4.0
Openshift: 4.10.30

Does this support the following:
1. Specifying multiple secrets (created on Azure key vault) in "AzureKeyVaultSecret" yaml definition, if so please share an example
2. Automatic sync of ALL secrets (created on Azure key vault) as openshift secrets?

**Comment by tspearconquest** [comment]
Neither of these is supported, I'm afraid; you need a 1:1 mapping secret in keyvault and AzureKeyVaultSecret resource in cluster
