### ISSUE TITLE
akv2k8s cannot authenticate on RBAC enabled Key Vault

### ISSUE THREAD

**Issue by shiangoli** [SparebankenVest/akv2k8s-website#72]
Hi All, I'm having issues with getting the akv2k8s service to authenticate on Azure Key Vault to retrieve certificate. In the namespace a kubectl describe on azurekeyvaultsecret.spv.no/certificate-sync revealed the following issue
azurekeyvaultcontroller  Failed to get secret for 'certificate-sync' from Azure Key Vault
RESPONSE 403: 403 Forbidden
ERROR CODE: Forbidden
 "error": {
    "code": "Forbidden",
    "message": "Caller is not authorized to perform action on resource.\r\nIf role assignments 
    DecisionReason: 'DeniedWithNoValidRBAC'
 
My Azure Kubernetes cluster identity is based on Service Principal, running the following gave me the identifier
az aks show -g <resource group name> -n <cluster name> --query "servicePrincipalProfile"

When I look inside Access control for the Key Vault specifically for the principal its assigned the role "Key Vault Certificates Officer" I've also tried using "Key Vault Secrets User" but got the same error. 
I tested the above roles on a user and they were able to access and download the certificate. I'm confused what the issue is and perhaps someone may be able to point me in the right direction. Thank you for your time

**Comment by Shiangoli-Jacobs** [comment]
I was able to resolve the issue. You need to have both roles assigned to the service principal to be able to read a certificate, "Key Vault Certificates Officer" and "Key Vault Secrets User"

**Comment by shiangoli** [comment]
Resolved the issue by assigning both roles to the service principal Key Vault Certificates Officer" and "Key Vault Secrets User"

**Comment by tspearconquest** [comment]
Voting to close as issue resolved by user

**Comment by shiangoli** [comment]
closing issue
