### ISSUE TITLE
I'm creating the self signed certificate and uploading the same key and server certificate in AKV. 

### ISSUE THREAD

**Issue by vijaykumarv7** [SparebankenVest/akv2k8s-website#74]
How do I consume the key and certificate create it as tls secret type secret in AKS.

like below comment.

kubectl create secret tls nginxtlssecret --key xxx.key --cert yyy.crt.

Please help with above query.

**Comment by tspearconquest** [comment]
https://akv2k8s.io/tutorials/sync/2-certificate/
